### ISSUE TITLE
Problem with pkl file

### ISSUE THREAD

**Issue by miguelgcasado** [sertansenturk/tomato#85]
Hi,
I've already installed tomato,essentia and the mcr of Matlab. Once I am running the first notebook of audio_analysis, I'm getting this error with the pkl file. How could I solve it?

I am using Ubuntu 18.04 with python 3.6.
![captura de pantalla de 2018-12-19 14-15-20](https://user-images.githubusercontent.com/33963843/50514686-20a15580-0aa0-11e9-8d78-f48c3e464291.png)

**Comment by sertansenturk** [comment]
Thank you @miguelgcasado for reporting the issue. I have realized that I deleted the pickle by mistake in a previous commit. I have reuploaded it to master: 3b182e1043da18337ec1f2bfb5d0bf0f8c62d3a4

Please do not hesitate to write if you have any other problems. I may not respond during weekdays due to my day job, but I will try to solve them over the weekends!
